---
version: '3'
services:
  buildwar:
    build:
      context: ./
      dockerfile: buildwar.Dockerfile
    volumes:
      - './app:/tmp'
    command: /bin/bash

  tomcat:
    build:
      context: ./
      dockerfile: tomcat.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './app:/tmp'
    depends_on:
      - buildwar
...