---
# version: '3'
#yaml: the attribute `version` is obsolete, it will be ignored,
#please remove it to avoid potential confusion
services:
  buildwar:
    build:
      context: ./
      dockerfile: buildwar.Dockerfile
    volumes:
      - swapdir:/tmp/shared
    command: tail -f /dev/null

  tomcat:
    build:
      context: ./
      dockerfile: tomcat.Dockerfile
    depends_on:
      - buildwar
    ports:
      - '8080:8080'
    volumes:
      - swapdir:/tmp/shared
    command: >
      cp /tmp/shared/hello-1.0.war /opt/apache-tomcat-9.0.34/webapps &&
      tail -f /dev/null

volumes:
  swapdir:
...