---
# version: '3'
#yaml: the attribute `version` is obsolete, it will be ignored,
#please remove it to avoid potential confusion
services:
  buildwar:
    build:
      context: ./
      dockerfile: buildwar.Dockerfile
    volumes:
      - app:/tmp
    command:
      'tail -f /dev/null'

  tomcat:
    build:
      context: ./
      dockerfile: tomcat.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - app:/webapps
    depends_on:
      - buildwar
    command:
      'tail -f /dev/null'

volumes:
  app:
...