---
version: '3'
services:
  buildwar:
    build:
      context: ./
      dockerfile: buildwar.Dockerfile
    volumes:
      - './app:/tmp'

  tomcat:
    build:
      context: ./
      dockerfile: tomcat.Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - './app:/webapps'
    depends_on:
      - buildwar
    command:
      'tail -f /dev/null'
...